[tool.black]
line-length = 100
target-version = ["py311"]
exclude = ["playwright-report", "test-results"]

[tool.isort]
profile = "black"
line_length = 100
skip = ["playwright-report", "test-results"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203","W503"]
exclude = ["playwright-report","test-results",".venv"]
